### PR TITLE
hide search icon from live until search feature is available

### PR DESCRIPTION
**Pull request by abhinav098**
hello team, this PR is to hide search icon from live app until search feature is available, please review

### CODE REVIEW

**Comment by Darshan-Chauhan** [comment]
Add a comment for reason behind commenting specific part of code.

**Comment by abhinav098** [comment]
@Darshan-Chauhan , I have already mentioned that in the description

**Comment by Darshan-Chauhan** [comment]
@abhinav098 , you need to add comment in code otherwise in future if someone stumbles upon this code then they'll will have to go through commits to find out the reason for commenting.

So it's always good idea to add comment as a reason for commenting the code with ticket number in comment.

**Comment by abhinav098** [comment]
ohh, you meant code, I thought comment on PR, sorry for misunderstanding @Darshan-Chauhan :P

**Pull request merged**
