### PR TITLE
Homepage responsive fixes

### PR DESCRIPTION
**Pull request by patrixr**
Text should not overflow off the screen anymore, and the content should shift left when the sidebar is open on the right side

### CODE REVIEW

**Comment by Darshan-Chauhan** [comment]
Hey @patrixr , I noticed in Home.hbs there are many issues regarding responsiveness on staging and frankly I think adding some foundation properties will improve them a lot.
For example, we use **row, columns, small, medium and large** classes from foundation(similar to bootstrap) to make page responsive.

You can do something like this

```
<div class="row">//every row can be divided in 12 columns
  <div class="small-4 medium-4 large-4 columns">//these small/medium/large will add responsiveness for same screen sizes
    ---- some text ---
  </div>
  <div class="small-6 medium-6 large-6 columns">
    --- some text ---
  </div>
  <div class="small-2 medium-2 large-2 columns">
    --- some text ---
  </div>
</div>
```

This is just the sample code I've added. 
For more info you can check foundation docs. :)
Foundation doc link:- https://foundation.zurb.com/sites/docs/

Note: We use foundation 5 I think and this is the link to foundation 6 docs.

**Comment by Darshan-Chauhan** [comment]
@patrixr, can you fix up the 4 space indentation in Home.hbs?? 😄

**Comment by patrixr** [comment]
> @patrixr, can you fix up the 4 space indentation in Home.hbs as well as scss file(I noticed 2 spaces at some places and 4 at other)?? 😄

Done

**Comment by namrataukirde** [comment]
👍

**Pull request merged**
