### PR TITLE
GCW:2439 Sorted district selection

### PR DESCRIPTION
**Pull request by Darshan-Chauhan**
Hi Team,

This PR sorts districts alphabetically.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2439

Please review

### CODE REVIEW

**Comment by abhinav098** [comment]
This looks great. We need to do the same changes for stock app also @Darshan-Chauhan.

**Comment by patrixr** [comment]
> This looks great. We need to do the same changes for stock app also @Darshan-Chauhan.

would it maybe have been easier to do it on api side ?

**Comment by abhinav098** [comment]
> would it maybe have been easier to do it on api side ?

Yes @patrixr that can also be done. Either we need to sort districts on the API or on the client. Simpler will be API, as we won't need to sort them on client side repeatedly. 

cc- @Darshan-Chauhan

**Comment by Darshan-Chauhan** [comment]
@abhinav098 , there is issue with serializer if we sort district so I did on client side. I'll do it on stock too.

**Comment by abhinav098** [comment]
👍

**Comment by patrixr** [comment]
> @abhinav098 , there is issue with serializer if we sort district so I did on client side. I'll do it on stock too.

Those serializers are evil : )

**Comment by steveyken** [comment]
I would generally leave sorting to the apps to do unless sending an `'?order=created_at` etc param but agree we have enough issues with serializers at the moment to warrant doing it solely client side. For small payloads like this, it'll be fine.

**Pull request merged**
